[package]
name = "language-lilypad"
version = "0.1.0"
authors = ["juleshenry"]
edition = "2021"
path = "src/main.rs"

[dependencies]
sycamore = "0.8"
wasm-bindgen = "0.2.83"
tikv-client-ffi = { git = "https://github.com/tikv/tikv.git", branch = "master" }
